### ISSUE TITLE
need to upload the selected document

### ISSUE THREAD

**Issue by Atominac** [sidlatau/flutter_document_picker#23]

**Comment by VyasPrachi** [comment]
Hello, 
I have applied same code but I am getting below error:
**I/flutter ( 5055): MissingPluginException(No implementation found for method pickDocument on channel flutter_document_picker)**

Please help me out

**Comment by sidlatau** [comment]
The plugin apparently hasn't been registered on the platform side. A few questions:
 
 1. Does it fail on iOS, Android, or both?
 2. Have you executed `flutter run` targeting that platform since you changed the pubspec file? This is needed to have Flutter inject plugin dependencies into the platform-specific parts of your app. _Please note that hot restart/hot reload is not enough to trigger the injection_.
 3. Does the `GeneratedPluginRegistrant` file that `flutter run` should have generated in your project contain a line registering the path provider plugin?
 4. Does your `AppDelegate.m` (iOS) or `MainActivity.java` (Android) contain a call to `GeneratedPluginRegistrant` asking it to register itself? Those calls should be made from the app launch method (`application:didFinishLaunchingWithOptions:` on iOS, `onCreate` on Android) as exemplified [here](https://github.com/flutter/plugins/blob/master/packages/path_provider/example).
