### ISSUE TITLE
Error on iOS

### ISSUE THREAD

**Issue by Arno-Z** [sidlatau/flutter_document_picker#26]
Hi,

I get this error:

Launching lib/main.dart on iPhone Xs in debug mode...
Running Xcode build...
Xcode build done.                                            3.4s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 4.0, 4.2, 5.0. This setting can be set in the build settings editor.

![image](https://user-images.githubusercontent.com/17185994/58131442-fc950b00-7c1e-11e9-980e-20d0091fb4d4.png)

Apparently a setting is missing from the picker?

Thanks!

Arno

**Comment by chelito-gajardo** [comment]
This problem is on the flutter side, so all plugins created with swift have the same problem. https://github.com/flutter/flutter/issues/25676#issuecomment-449543241

You need to make some settings to solve this.

1. Bridging Header must be created.
Open the project with XCode.
Then choose File -> New -> File -> Swift File on Runner holder.
Create the swift file(), then also create Bridging Header, click it on a dialog.

2. Make sure you have use_frameworks! in the Runner block, in ios/Podfile.
```
target 'Runner' do
  use_frameworks!
```
3. Execute **flutter clean**
4. Go to your ios folder, delete Podfile.lock and Pods folder and then execute **pod install --repo-update**

That's work for me.
Hope this helps you!

**Comment by Arno-Z** [comment]
Thanks, i'll give that a try.

**Comment by sidlatau** [comment]
Thanks, @chelito-gajardo  for a detailed explanation.

**Comment by sumbang** [comment]
thanks @chelito-gajardo you save me !!
